apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-green
  labels:
    app: myapp-deployment-green
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        version: green
    spec:
      containers:
        - name: myapp-container
          image: hitanshu91/sample-application-green-version:v1
  replicas: 1
  selector:
    matchLabels:
      version: green
      app: myapp