steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ey-demo-proj/blue-app:V01', '-f', './Blue-Application/Dockerfile', './Blue']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ey-demo-proj/green-app:V01', '-f', './Green-Application/Dockerfile', './Green']

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - './Kubernetes-YAML/blue-version-deployment.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=ey-task-cluster'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - './Kubernetes-YAML/green-version-deployment.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=ey-task-cluster'
